spring:
  application:
    name: livrariaapi
  datasource:
    url: jdbc:postgresql://localhost:5432/livrariadb
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

